---
title: "someExamples"
author: "Dr K"
date: "September 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tigerstats)
data(m111surveyfa12)
data(imagpop)
```

## look at the survey and imagepop


```{r }
View(m111surveyfa13)
View(imagpop)
```

## explore kkardashtemp in imagepop

You can also embed plots, for example:

```{r }
plot(imagpop$kkardashtemp)
hist(imagpop$kkardashtemp)
plot(density(imagpop$kkardashtemp))
```

## Try taking means of samples of size 2, size 3 and size 4 and look at the shapes of their distributions.


## Here is what you get for samples of size 2



```{r}
size2means=numeric()
for (i in 1:1000){
size2means[i] <-  mean(sample(imagpop$kkardashtemp,size=2))
}
plot(density(size2means))
```
## samples of size 3


```{r}
size3means=numeric()
for (i in 1:1000){
size3means[i] <-  mean(sample(imagpop$kkardashtemp,size=3))
}
plot(density(size3means))
```
## samples of size 7
```{r}
size7means=numeric()
for (i in 1:1000){
size7means[i] <-  mean(sample(imagpop$kkardashtemp,size=7))
}
plot(density(size7means))
```

```{r}
size30means=numeric()
for (i in 1:1000){
size30means[i] <-  mean(sample(imagpop$kkardashtemp,size=30))
}
plot(density(size30means))
```

```{r}
size200means=numeric()
for (i in 1:1000){
size200means[i] <-  mean(sample(imagpop$kkardashtemp,size=200))
}
plot(density(size200means))
```




